-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "first_name" character varying NULL, "last_name" character varying NULL, "email" character varying NOT NULL, "location" character varying NULL, "phone" character varying NULL, "password" character varying NOT NULL, "status" boolean NOT NULL DEFAULT true, PRIMARY KEY ("id"));
-- create index "users_first_name_key" to table: "users"
CREATE UNIQUE INDEX "users_first_name_key" ON "users" ("first_name");
-- create index "users_last_name_key" to table: "users"
CREATE UNIQUE INDEX "users_last_name_key" ON "users" ("last_name");
-- create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
